name: Python & Selenium CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Chromium and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          # Only create symlink if it doesn't exist
          if [ ! -f /usr/bin/chromedriver ]; then
            sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
          fi

      - name: Start FastAPI app
        run: uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        shell: bash

      - name: Wait for server to be ready
        run: |
          sleep 5
          curl --retry 5 --retry-connrefused --retry-delay 2 http://localhost:8000/signup

      - name: Run tests
        env:
          PATH: /usr/lib/chromium-browser:$PATH
        run: pytest
