name: Python & Selenium CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

      - name: Start FastAPI app
        run: uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        shell: bash

      - name: Run tests
        env:
          PATH: /usr/lib/chromium-browser:$PATH
        run: pytest
